{"uuid": "62374dd8-b408-4d9f-bdde-1520c92e095f", "children": ["33ebf608-97ff-4757-a33c-3acf04296053"], "befores": [{"name": "driverenv", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at 'D://Users//Mika//PycharmProjects//appauto//data//apk//jumei.apk' does not exist or is not accessible\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: The application at 'D://Users//Mika//PycharmProjects//appauto//data//apk//jumei.apk' does not exist or is not accessible\n    at getResponseForW3CError (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\n", "trace": "  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\base\\conftest_android.py\", line 46, in driverenv\n    driver = webdriver.Remote(host, capabilities)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 230, in __init__\n    super().__init__(\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 320, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1658316128720, "stop": 1658316130802}], "start": 1658316128720, "stop": 1658316130945}