{"uuid": "1c383deb-cca3-4953-bbd4-b224fb830a4b", "children": ["060f58f8-9a81-4d32-a532-d38bfbd23585"], "befores": [{"name": "driverenv", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022B218DDA20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))\n", "trace": "  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\base\\conftest_android.py\", line 47, in driverenv\n    driver = webdriver.Remote(host, capabilities)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 230, in __init__\n    super().__init__(\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 320, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 433, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 344, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 366, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1658385972693, "stop": 1658385988735}], "start": 1658385972693, "stop": 1658385988981}