{"uuid": "e549bdaf-9ee4-4b20-832f-65bf4a0c517d", "children": ["b56a48c2-37b8-4f21-9b39-e042f3c2db05"], "befores": [{"name": "driverenv", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.qooapp.qoohelper.testfairy' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'com.qooapp.qoohelper.testfairy' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.com.qooapp.qoohelper.arch.welcome.WelcomeActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.qooapp.qoohelper.testfairy' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'com.qooapp.qoohelper.testfairy' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.com.qooapp.qoohelper.arch.welcome.WelcomeActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity\n    at getResponseForW3CError (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (D:\\Program Files\\nodejs\\node_global\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\n", "trace": "  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\base\\conftest_android.py\", line 48, in driverenv\n    driver = webdriver.Remote(host, capabilities)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 230, in __init__\n    super().__init__(\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 320, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Users\\Mika\\PycharmProjects\\py_appauto\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1658393143372, "stop": 1658393154241}], "start": 1658393143372, "stop": 1658393154440}